# Generated by Django 5.0.6 on 2024-06-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appobject',
            name='object_key',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
