# Generated by Django 5.0.6 on 2024-06-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_appuser_is_email_verified'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
            ],
        ),
    ]
